services:
  db:
    image: ankane/pgvector
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: similarity-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
